In [1]:
import os
import numpy as np
from sklearn import mixture
import pandas as pd
import re

In [2]:
#change path
path="..\\keystroke.csv"

In [3]:
import pandas
import numpy as np
data = pandas.read_csv(path)
subjects = data["subject"].unique()

In [4]:
subjects

array(['s002', 's003', 's004', 's005', 's007', 's008', 's010', 's011',
       's012', 's013', 's015', 's016', 's017', 's018', 's019', 's020',
       's021', 's022', 's024', 's025', 's026', 's027', 's028', 's029',
       's030', 's031', 's032', 's033', 's034', 's035', 's036', 's037',
       's038', 's039', 's040', 's041', 's042', 's043', 's044', 's046',
       's047', 's048', 's049', 's050', 's051', 's052', 's053', 's054',
       's055', 's056', 's057'], dtype=object)

In [5]:

mean_vector = []

In [6]:
from sklearn.mixture import GMM
import pandas 
#from EER_GMM import evaluateEER
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [7]:
def training(train):
    gmm = GMM(n_components = 2, covariance_type = 'diag', 
                    verbose = False )
    gmm.fit(train)
    return gmm

In [8]:
def testing(test_genuine, test_imposter, gmm):
    user_scores = []
    imposter_scores = []
    for i in range(test_genuine.shape[0]):
        j = test_genuine.iloc[i].values
        cur_score = gmm.score([j])
        user_scores.append(cur_score)

    for i in range(test_imposter.shape[0]):
        j = test_imposter.iloc[i].values
        cur_score = gmm.score([j])
        imposter_scores.append(cur_score)
        
    return user_scores, imposter_scores

In [9]:
def evaluateEERGMM(user_scores, imposter_scores):
    thresholds = range(20,51)
    array = np.zeros((len(thresholds),3))
    i = 0
    for th in thresholds:
        g_i = 0
        i_g = 0
        for score in user_scores:
            if score < th:
                g_i = g_i + 1
        for score in imposter_scores:    
            if score > th:
                i_g = i_g + 1

        FA = float(i_g) / len(imposter_scores) 
        FR = float(g_i) / len(user_scores)
        array[i, 0] = th
        array[i, 1] = FA
        array[i, 2] = FR
        i = i + 1
    
    for j in range(array.shape[0]):
        if array[j,1] < array[j,2]:
            thresh = (array[j,0] + array[j - 1, 0]) / 2
            break
    g_i = 0
    i_g = 0
    for score in user_scores:
        if score < thresh:
            g_i = g_i + 1
    for score in imposter_scores:    
        if score > thresh:
            i_g = i_g + 1

    FA = float(i_g) / len(imposter_scores) 
    FR = float(g_i) / len(user_scores)
    return (FA + FR) /2
    

In [10]:
def evaluate(subjects):    
    eers = []

    for subject in subjects:        
        genuine_user_data = data.loc[data.subject == subject, \
                                     "H.period":"H.Return"]
        imposter_data = data.loc[data.subject != subject, :]

        train = genuine_user_data[:200]
        test_genuine = genuine_user_data[200:]
        test_imposter = imposter_data.groupby("subject"). \
                             head(5).loc[:, "H.period":"H.Return"]

        gmm = training(train)
        user_scores, imposter_scores = testing(test_genuine, test_imposter, gmm)
        eers.append(evaluateEERGMM(user_scores, imposter_scores))
    return np.mean(eers)

In [11]:
print ("average EER for GMM detector:")

print(evaluate(subjects))

average EER for GMM detector:
0.13268627450980394


In [12]:
subject = subjects[0]
subject


's002'

In [13]:
genuine_user_data = data.loc[data.subject == subject, \
                             "H.period":"H.Return"]
genuine_user_data

H.period  DD.period.t  UD.period.t     H.t  DD.t.i  UD.t.i     H.i  \
0      0.1491       0.3979       0.2488  0.1069  0.1674  0.0605  0.1169   
1      0.1111       0.3451       0.2340  0.0694  0.1283  0.0589  0.0908   
2      0.1328       0.2072       0.0744  0.0731  0.1291  0.0560  0.0821   
3      0.1291       0.2515       0.1224  0.1059  0.2495  0.1436  0.1040   
4      0.1249       0.2317       0.1068  0.0895  0.1676  0.0781  0.0903   
5      0.1394       0.2343       0.0949  0.0813  0.1299  0.0486  0.0744   
6      0.1064       0.2069       0.1005  0.0866  0.1368  0.0502  0.0800   
7      0.0929       0.1810       0.0881  0.0818  0.1378  0.0560  0.0747   
8      0.0966       0.1797       0.0831  0.0771  0.1296  0.0525  0.0839   
9      0.1093       0.1807       0.0714  0.0731  0.1457  0.0726  0.0766   
10     0.0887       0.1660       0.0773  0.0876  0.1560  0.0684  0.0839   
11     0.0911       0.1525       0.0614  0.0824  0.1516  0.0692  0.0731   
12     0.1114       0.1620       0.0506  0.0900  0.1547  0.0647  0.0797   
13     0.0903       0.1871       0.0968  0.0805  0.1919  0.1114  0.0842   
14     0.1169       0.2562       0.1393  0.0739  0.1549  0.0810  0.0892   
15     0.1270       0.1839       0.0569  0.0911  0.1381  0.0470  0.0895   
16     0.1016       0.1799       0.0783  0.0792  0.1434  0.0642  0.0760   
17     0.1056       0.1755       0.0699  0.0781  0.1391  0.0610  0.0898   
18     0.1177       0.2237       0.1060  0.0837  0.1880  0.1043  0.0919   
19     0.1027       0.1781       0.0754  0.0729  0.1418  0.0689  0.0792   
20     0.1016       0.1374       0.0358  0.0861  0.1629  0.0768  0.0774   
21     0.1072       0.2217       0.1145  0.0726  0.1349  0.0623  0.0768   
22     0.1243       0.1841       0.0598  0.0768  0.1568  0.0800  0.0850   
23     0.1241       0.2019       0.0778  0.0829  0.1745  0.0916  0.0734   
24     0.1098       0.1567       0.0469  0.0768  0.1642  0.0874  0.0605   
25     0.0916       0.1691       0.0775  0.0818  0.1502  0.0684  0.0721   
26     0.1272       0.1950       0.0678  0.0824  0.1442  0.0618  0.0776   
27     0.0874       0.1726       0.0852  0.0747  0.1243  0.0496  0.0758   
28     0.0948       0.1979       0.1031  0.0760  0.1412  0.0652  0.0776   
29     0.1196       0.1356       0.0160  0.0890  0.1666  0.0776  0.0742   
..        ...          ...          ...     ...     ...     ...     ...   
370    0.1597       0.2005       0.0408  0.0760  0.1753  0.0993  0.0908   
371    0.1433       0.1271      -0.0162  0.0937  0.1877  0.0940  0.0977   
372    0.1526       0.1546       0.0020  0.1193  0.1695  0.0502  0.1101   
373    0.1679       0.2056       0.0377  0.1006  0.1371  0.0365  0.1256   
374    0.1636       0.3224       0.1588  0.1119  0.2085  0.0966  0.1167   
375    0.1307       0.1436       0.0129  0.1088  0.1537  0.0449  0.1135   
376    0.1570       0.1865       0.0295  0.1204  0.1555  0.0351  0.1299   
377    0.1283       0.1818       0.0535  0.1177  0.1660  0.0483  0.1074   
378    0.1383       0.1469       0.0086  0.1016  0.1594  0.0578  0.1111   
379    0.1454       0.1894       0.0440  0.1066  0.1465  0.0399  0.1281   
380    0.1705       0.2237       0.0532  0.1019  0.1457  0.0438  0.1157   
381    0.1544       0.1876       0.0332  0.1404  0.1642  0.0238  0.1399   
382    0.1648       0.1509      -0.0139  0.1228  0.1321  0.0093  0.1433   
383    0.2093       0.1815      -0.0278  0.1074  0.1457  0.0383  0.1172   
384    0.1755       0.1926       0.0171  0.1006  0.1838  0.0832  0.0969   
385    0.1412       0.1498       0.0086  0.1354  0.1565  0.0211  0.1167   
386    0.1483       0.1733       0.0250  0.1072  0.1634  0.0562  0.0966   
387    0.1531       0.1752       0.0221  0.0839  0.1309  0.0470  0.0924   
388    0.1198       0.1519       0.0321  0.1072  0.2181  0.1109  0.0555   
389    0.1362       0.1989       0.0627  0.1196  0.1553  0.0357  0.1212   
390    0.1557       0.2169       0.0612  0.1214  0.1827  0.0613  0.1138   
391    0.1528       0.1654    

In [14]:
imposter_data = data.loc[data.subject != subject, :]
imposter_data

subject  sessionIndex  rep  H.period  DD.period.t  UD.period.t     H.t  \
400      s003             1    1    0.1333       0.2636       0.1303  0.1246   
401      s003             1    2    0.1307       0.3850       0.2543  0.1214   
402      s003             1    3    0.1143       0.2752       0.1609  0.1148   
403      s003             1    4    0.1328       0.2296       0.0968  0.0985   
404      s003             1    5    0.1217       0.1863       0.0646  0.1175   
405      s003             1    6    0.1320       0.1979       0.0659  0.1217   
406      s003             1    7    0.1235       0.2285       0.1050  0.0913   
407      s003             1    8    0.1190       0.3878       0.2688  0.1032   
408      s003             1    9    0.0921       0.2741       0.1820  0.1172   
409      s003             1   10    0.1283       0.6059       0.4776  0.1246   
410      s003             1   11    0.1336       0.3019       0.1683  0.1272   
411      s003             1   12    0.1143       0.5562       0.4419  0.1483   
412      s003             1   13    0.1204       0.2393       0.1189  0.1491   
413      s003             1   14    0.1291       0.2008       0.0717  0.1528   
414      s003             1   15    0.1180       0.8536       0.7356  0.1296   
415      s003             1   16    0.0998       0.2678       0.1680  0.1227   
416      s003             1   17    0.1077       0.5327       0.4250  0.1201   
417      s003             1   18    0.1415       0.2166       0.0751  0.1362   
418      s003             1   19    0.1106       0.4335       0.3229  0.1278   
419      s003             1   20    0.1317       0.2100       0.0783  0.1280   
420      s003             1   21    0.1196       0.2027       0.0831  0.1109   
421      s003             1   22    0.1217       0.2135       0.0918  0.1204   
422      s003             1   23    0.1388       0.1857       0.0469  0.1307   
423      s003             1   24    0.1251       0.2071       0.0820  0.1405   
424      s003             1   25    0.1214       0.3762       0.2548  0.1420   
425      s003             1   26    0.1636       0.2116       0.0480  0.0837   
426      s003             1   27    0.1227       0.2000       0.0773  0.1140   
427      s003             1   28    0.1470       0.1599       0.0129  0.1357   
428      s003             1   29    0.1375       0.1799       0.0424  0.1138   
429      s003             1   30    0.1454       0.2936       0.1482  0.1454   
...       ...           ...  ...       ...          ...          ...     ...   
20370    s057             8   21    0.0657       0.0894       0.0237  0.0979   
20371    s057             8   22    0.0670       0.0988       0.0318  0.0905   
20372    s057             8   23    0.0874       0.0717      -0.0157  0.0926   
20373    s057             8   24    0.0890       0.0854      -0.0036  0.0826   
20374    s057             8   25    0.0675       0.1030       0.0355  0.0845   
20375    s057             8   26    0.0886       0.1233       0.0347  0.0834   
20376    s057             8   27    0.0840       0.0783      -0.0057  0.0995   
20377    s057             8   28    0.0678       0.1073       0.0395  0.0897   
20378    s057             8   29    0.0789       0.3275       0.2486  0.0860   
20379    s057             8   30    0.1097       0.1186       0.0089  0.1050   
20380    s057             8   31    0.0802       0.1089       0.0287  0.0971   
20381    s057             8   32    0.0923       0.1004       0.0081  0.0952   
20382    s057             8   33    0.0857       0.1133       0.0276  0.0907   
20383    s057             8   34    0.0818       0.1606       0.0788  0.0499   
20384    s057             8   35    0.0834       0.1179       0.0345  0.0979   
20385    s057             8   36    0.0884       0.3681       0.2797  0.0921   
20386    s057             8   37    0.0749       0.1065       0.0316  0.0989   
20387    s057             8   38    0.0786       0.1004       0.0218  0.0973   
20388 

In [15]:
train = genuine_user_data[:200]


In [16]:
test_genuine = genuine_user_data[200:]
test_imposter = imposter_data.groupby("subject"). \
                     head(5).loc[:, "H.period":"H.Return"]

test_imposter

H.period  DD.period.t  UD.period.t     H.t  DD.t.i  UD.t.i     H.i  \
400      0.1333       0.2636       0.1303  0.1246  0.1737  0.0491  0.1330   
401      0.1307       0.3850       0.2543  0.1214  0.1908  0.0694  0.0956   
402      0.1143       0.2752       0.1609  0.1148  0.1439  0.0291  0.1468   
403      0.1328       0.2296       0.0968  0.0985  0.7023  0.6038  0.1222   
404      0.1217       0.1863       0.0646  0.1175  0.1584  0.0409  0.1175   
800      0.0937       0.4301       0.3364  0.0961  0.1803  0.0842  0.0808   
801      0.1183       0.6046       0.4863  0.0634  0.1371  0.0737  0.0927   
802      0.0998       0.2984       0.1986  0.0673  0.1257  0.0584  0.0934   
803      0.1027       0.4225       0.3198  0.0858  0.1175  0.0317  0.1048   
804      0.1072       0.2763       0.1691  0.0950  0.1850  0.0900  0.1003   
1200     0.0729       0.2393       0.1664  0.1254  0.3416  0.2162  0.0853   
1201     0.0721       0.9983       0.9262  0.1077  0.3803  0.2726  0.0752   
1202     0.0631       1.2671       1.2040  0.1362  0.3254  0.1892  0.0792   
1203     0.1040       0.6528       0.5488  0.1288  0.4310  0.3022  0.0977   
1204     0.0837       0.6212       0.5375  0.1090  0.4267  0.3177  0.0924   
1600     0.0818       0.2332       0.1514  0.0607  0.1101  0.0494  0.1074   
1601     0.0913       0.2649       0.1736  0.0713  0.1938  0.1225  0.0475   
1602     0.0800       0.3990       0.3190  0.0686  0.1080  0.0394  0.1130   
1603     0.0718       0.8027       0.7309  0.0655  0.1465  0.0810  0.0832   
1604     0.0845       0.2594       0.1749  0.0507  0.0895  0.0388  0.0874   
2000     0.1003       0.2443       0.1440  0.0927  0.1062  0.0135  0.0755   
2001     0.1526       0.3373       0.1847  0.0866  0.0935  0.0069  0.0700   
2002     0.1296       0.3116       0.1820  0.0956  0.1125  0.0169  0.0871   
2003     0.1354       0.3367       0.2013  0.1000  0.2892  0.1892  0.1014   
2004     0.1307       0.3684       0.2377  0.1003  0.1077  0.0074  0.0832   
2400     0.1043       0.1755       0.0712  0.0562  0.1813  0.1251  0.0789   
2401     0.0850       0.1514       0.0664  0.0536  0.3695  0.3159  0.0742   
2402     0.0842       0.2881       0.2039  0.0700  0.1458  0.0758  0.0673   
2403     0.0855       0.1535       0.0680  0.0642  0.1883  0.1241  0.0847   
2404     0.0948       0.1264       0.0316  0.0539  0.1537  0.0998  0.0665   
...         ...          ...          ...     ...     ...     ...     ...   
18000    0.0551       0.6974       0.6423  0.0998  0.0789 -0.0209  0.1061   
18001    0.0594       1.6560       1.5966  0.1008  0.0757 -0.0251  0.1246   
18002    0.0554       0.8815       0.8261  0.0952  0.1438  0.0486  0.0288   
18003    0.0654       1.2264       1.1610  0.1113  0.0820 -0.0293  0.1338   
18004    0.0594       0.6023       0.5429  0.0747  0.0483 -0.0264  0.1083   
18400    0.1285       0.3009       0.1724  0.0615  0.0792  0.0177  0.1032   
18401    0.1137       0.2924       0.1787  0.0404  0.0629  0.0225  0.0770   
18402    0.1166       0.2239       0.1073  0.0483  0.0597  0.0114  0.0789   
18403    0.1100       0.1962       0.0862  0.0530  0.0544  0.0014  0.0766   
18404    0.1461       0.2869       0.1408  0.0446  0.0544  0.0098  0.0984   
18800    0.0902       0.4725       0.3823  0.0789  0.2567  0.1778  0.0871   
18801    0.0992       0.8167       0.7175  0.0768  0.1981  0.1213  0.0886   
18802    0.1082       0.8391       0.7309  0.0807  0.4299  0.3492  0.0525   
18803    0.1074       0.2882       0.1808  0.0678  0.1351  0.0673  0.0715   
18804    0.0934       1.1982       1.1048  0.0710  0.1757  0.1047  0.0886   
19200    0.0855       0.1598       0.0743  0.0897  0.1095  0.0198  0.0657   
19201    0.0871       0.1817       0.0946  0.0973  0.1158  0.0185  0.0633   
19202    0.0778       0.0980       0.0202  0.0675  0.1103  0.0428  0.0741   
19203    0.0873       0.2394       0.1521  0.0739  0.0816  0.0077  0.0689   
19204    0.0831       0.1806       0.0975  0.0947  0.0958  0.0011  0.0778   
196

In [17]:
gmm = GMM(n_components = 2, covariance_type = 'diag', verbose = False )
gmm.fit(train)
gmm

GMM(covariance_type='diag', init_params='wmc', min_covar=0.001,
  n_components=2, n_init=1, n_iter=100, params='wmc', random_state=None,
  tol=0.001, verbose=False)

In [18]:
user_scores, imposter_scores = testing(test_genuine, test_imposter, gmm)
imposter_scores


[array([43.36860091]),
 array([41.93577126]),
 array([35.30394054]),
 array([-138.63295814]),
 array([-37.8400682]),
 array([45.49788504]),
 array([33.7441285]),
 array([18.04749482]),
 array([43.65917184]),
 array([47.78350343]),
 array([-456.88710513]),
 array([-45.24212821]),
 array([-125.87022192]),
 array([-21.17157901]),
 array([-8.31715561]),
 array([28.63314349]),
 array([23.86628144]),
 array([24.90927436]),
 array([20.07122887]),
 array([40.05906835]),
 array([41.7156826]),
 array([40.25138188]),
 array([42.52625161]),
 array([40.69067002]),
 array([40.79359065]),
 array([39.26507693]),
 array([12.44810289]),
 array([35.60079248]),
 array([51.11046171]),
 array([51.64812107]),
 array([43.94746012]),
 array([53.82182446]),
 array([50.46278185]),
 array([43.05054085]),
 array([40.51064183]),
 array([29.18505221]),
 array([11.58751868]),
 array([24.96542346]),
 array([-86.8840574]),
 array([21.39391494]),
 array([31.67465599]),
 array([54.04482691]),
 array([35.09101915]),
 arra

In [19]:
gmm.score([test_genuine.iloc[0].values])

array([56.22601788])

In [21]:
gmm.score([test_imposter.iloc[20].values])

array([41.7156826])